name: Check for WIZ CFN Updates

on:
  push:
    branches:
      - main
    paths:
      - CFN_Template/**
  schedule:
    - cron: '0 0 * * 0' # Runs Weekly on Sunday at midnight
  workflow_dispatch: # Allows manual trigger

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout and actions/PR
  pull-requests: write # This is required to Write the PR Comment

jobs:
  wiz_integration_mgmt:
    name: Check Wiz CFN templates for updates
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: CFN_Template
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or any LTS version you prefer

    - name: Download the latest CFN template
      run: curl -o downloaded.json https://wizio-public.s3.amazonaws.com/deployment-v2/aws/wiz-aws-standard-org.json

    - name: Compare new CFN template against deployed one
      id: compare
      run: |
        # Normalize and compare JSON files
        if jq -S . downloaded.json > normalized_downloaded.json && \
           jq -S . wiz-aws-standard-org.json > normalized_existing.json && \
           ! diff -q normalized_downloaded.json normalized_existing.json > /dev/null; then
          echo "CHANGED=true" >> $GITHUB_ENV
        else
          echo "CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Update JSON file and commit changes
      if: env.CHANGED == 'true'
      run: |
        echo "Overwriting the existing JSON file..."
        cp downloaded.json wiz-aws-standard-org.json
        rm -rf downloaded.json normalized_downloaded.json normalized_existing.json

        git config --global user.name "GitHub Actions"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        echo "Checking for changes..."
        git status

        if git status --porcelain | grep wiz-aws-standard-org.json; then
          echo "Changes detected. Staging and committing changes."
          git add wiz-aws-standard-org.json
          git commit -m "Update JSON file"
        else
          echo "No changes to commit."
        fi

    - name: Create a branch and Pull Request
      if: env.CHANGED == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Update Wiz CFN Template file'
        body: 'This PR updates the CFN template file with the latest version for the Wiz integration.'
        reviewers: 'cyberviking949'

    - name: Configure AWS credentials
      if : github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-duration-seconds: 3600

    - name: Create CloudFormation Change Set
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      id: create_change_set # Assign an ID to reference outputs in later steps
      run: |
        CHANGE_SET=$(aws cloudformation create-change-set \
          --stack-name arn:aws:cloudformation:us-west-2:808696518247:stack/Wiz-io-SaaS-Connector/0dd68a00-ab72-11ef-a2c2-06c9bfb46c8f \
          --change-set-name UpdateIntegration \
          --no-use-previous-template \
          --template-url https://wizio-public.s3.amazonaws.com/deployment-v2/aws/wiz-aws-standard-org.json \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameters ParameterKey=ExternalId,UsePreviousValue=true \
                       ParameterKey=RoleARN,UsePreviousValue=true \
                       ParameterKey=WizRoleName,UsePreviousValue=true \
                       ParameterKey=DataScanning,UsePreviousValue=true \
                       ParameterKey=EKSScanning,UsePreviousValue=true \
                       ParameterKey=LightsailScanning,UsePreviousValue=true \
                       ParameterKey=S3AWSLogsScanning,UsePreviousValue=true \
                       ParameterKey=RDSLogsScanning,UsePreviousValue=true \
                       ParameterKey=S3KMSDecrypt,UsePreviousValue=true \
                       ParameterKey=isOrg,UsePreviousValue=true \
                       ParameterKey=orgId,UsePreviousValue=true)
        echo "$CHANGE_SET" | jq -r '.Id' > change_set_arn.txt
              
    - name: Execute CloudFormation Change Set
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        CHANGE_SET_ARN=$(cat change_set_arn.txt)
        aws cloudformation execute-change-set --change-set-name "$CHANGE_SET_ARN"
