name: Check for WIZ CFN Updates

on:
    schedule:
      - cron: '0 0 * * 0' # Runs Weekly on Sunday at midnight
    workflow_dispatch: # Allows manual trigger

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout and actions/PR
  pull-requests: write # This is required to Write the PR Comment

jobs:
  wiz_integration_mgmt:
    name: Check Wiz CFN templates for updates
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: CFN_Template
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or any LTS version you prefer

    - name: Download the latest CFN template
      run: curl -o downloaded.json https://wizio-public.s3.amazonaws.com/deployment-v2/aws/wiz-aws-standard-org.json

    - name: Compare new CFN template against deployed one
      id: compare
      run: |
        # Normalize and compare JSON files
        if jq -S . downloaded.json > normalized_downloaded.json && \
           jq -S . wiz-aws-standard-org.json > normalized_existing.json && \
           ! diff -q normalized_downloaded.json normalized_existing.json > /dev/null; then
          echo "CHANGED=true" >> $GITHUB_ENV
        else
          echo "CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Update JSON file and commit changes
      if: env.CHANGED == 'true'
      run: |
        echo "Overwriting the existing JSON file..."
        cp downloaded.json wiz-aws-standard-org.json
        rm -rf downloaded.json normalized_downloaded.json normalized_existing.json

        git config --global user.name "GitHub Actions"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        echo "Checking for changes..."
        git status

        if git status --porcelain | grep wiz-aws-standard-org.json; then
          echo "Changes detected. Staging and committing changes."
          git add wiz-aws-standard-org.json
          git commit -m "Update JSON file"
        else
          echo "No changes to commit."
        fi

    - name: Create a branch and Pull Request
      if: env.CHANGED == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Update Wiz CFN Template file'
        body: 'This PR updates the CFN template file with the latest version for the Wiz integration.'
        reviewers: 'cyberviking949'

    - name: Configure AWS credentials
      if : github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ secrets.AWS_ROLE }}
        role-duration-seconds: 3600

    - name: Update CloudFormation stack
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        'aws cloudformation update-stack \
        --stack-set-name Wiz-io-SaaS-Connector \
        --no-use-previous-template \
        --template-url https://wizio-public.s3.amazonaws.com/deployment-v2/aws/wiz-aws-standard-org.json \
        --capabilities CAPABILITY_NAMED_IAM
