name: Check for WIZ CFN Updates

on:
    schedule:
      - cron: '0 0 * * *' # Runs daily at midnight
    workflow_dispatch: # Allows manual trigger

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
  pull-requests: write # This is required to Write the PR Comment

jobs:
  terraform_deploy:
    name: Check Wiz CFN templates for updates
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: CFN_Template
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    # - name: configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-region: 'us-east-1'
    #     role-to-assume: ${{ secrets.AWS_ROLE }}
    #     role-duration-seconds: 3600

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or any LTS version you prefer

    - name: Download the latest JSON file
      run: curl -o downloaded.json https://wizio-public.s3.amazonaws.com/deployment-v2/aws/wiz-aws-standard-org.json

    - name: Compare JSON files
      id: compare
      run: |
        # Normalize and compare JSON files
        if jq -S . downloaded.json > normalized_downloaded.json && \
           jq -S . wiz-aws-standard-org.json > normalized_existing.json && \
           ! diff -q normalized_downloaded.json normalized_existing.json > /dev/null; then
          echo "CHANGED=true" >> $GITHUB_ENV
        else
          echo "CHANGED=false" >> $GITHUB_ENV
        fi

    - name: Update JSON file and create a new branch
      if: env.CHANGED == 'true'
      run: |
        echo "Overwriting the existing JSON file..."
        cp downloaded.json wiz-aws-standard-org.json
        rm -rf normalized_downloaded.json normalized_existing.json downloaded.json

        git config --global user.name "GitHub Actions"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        echo "Checking out a new branch..."
        branch_name="update-json-$(date +'%Y%m%d%H%M%S')"
        echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV
        git checkout -b $branch_name

        echo "Checking for changes..."
        git status

        if git status --porcelain | grep wiz-aws-standard-org.json; then
          echo "Changes detected. Staging and committing changes."
          git add wiz-aws-standard-org.json
          git commit -m "Update JSON file"
        else
          echo "No changes to commit."
        fi

        echo "Pushing branch: $branch_name"
        git push origin $branch_name

    - name: Verify Branch State
      run: |
        echo "Verifying branch: ${{ env.BRANCH_NAME }}"
        git checkout ${{ env.BRANCH_NAME }}
        git log -1
        echo "Contents of the updated JSON file:"
        cat wiz-aws-standard-org.json

    - name: Create a Pull Request
      if: env.CHANGED == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.BRANCH_NAME }} # The branch containing the changes
        base: main                    # Target branch for the PR
        title: 'Update JSON file'
        body: 'This PR updates the JSON file with the latest version.'
        delete-branch: false          # Do not delete the branch after PR creation
