name: Check for WIZ CFN Updates

on:
    schedule:
      - cron: '0 0 * * *' # Runs daily at midnight
    workflow_dispatch: # Allows manual trigger

permissions:
  id-token: write # This is required for requesting the JWT
  contents: write  # This is required for actions/checkout
  pull-requests: write # This is required to Write the PR Comment

jobs:
  terraform_deploy:
    name: Check Wiz CFN templates for updates
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: CFN_Template
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3.3.0

    # - name: configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-region: 'us-east-1'
    #     role-to-assume: ${{ secrets.AWS_ROLE }}
    #     role-duration-seconds: 3600

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or any LTS version you prefer

    - name: Download the latest JSON file
      run: curl -o downloaded.json https://wizio-public.s3.amazonaws.com/deployment-v2/aws/wiz-aws-standard-org.json

    - name: Compare JSON files
      id: compare
      run: |
        echo "Checking if the JSON files are different using diff..."
        if diff downloaded.json wiz-aws-standard-org.json > /dev/null; then
          echo "Files are the same."
          echo "CHANGED=false" >> $GITHUB_ENV
        else
          echo "Files are different."
          echo "CHANGED=true" >> $GITHUB_ENV
        fi

    - name: Update JSON file and create a new branch
      if: env.CHANGED == 'true'
      run: |
        cp downloaded.json wiz-aws-standard-org.json
        git config --global user.name "GitHub Actions"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        branch_name="update-json"
        git checkout -b $branch_name
        git add .
        git commit -m "Update JSON file"
        git push origin $branch_name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Create a Pull Request
      if: env.CHANGED == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: $branch_name
        title: 'Update JSON file'
        body: 'This PR updates the JSON file with the latest version.'
        draft: false # Ensure the PR is created in normal (non-draft) mode
        reviewers: cyberviking949 # Add required reviewers here
        #team-reviewers: [] # Add required team reviewers here